# Generated by Django 6.0.3 on 2026-04-15 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vacancies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('requirements', models.TextField(max_length=200)),
                ('knowledge', models.TextField(max_length=200)),
                ('known_lnaguages', models.TextField(max_length=200)),
                ('skills', models.TextField(max_length=200)),
                ('company_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('work_of_experience', models.TextField(max_length=100)),
                ('contacts', models.TextField(max_length=100)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.TimeField(auto_now_add=True)),
                ('updated_at', models.TimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.category')),
            ],
        ),
    ]
