# Generated by Django 6.0.3 on 2026-04-15 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacancies',
            old_name='name',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='vacancies',
            name='salary',
            field=models.IntegerField(),
        ),
    ]
