# Generated by Django 6.0.3 on 2026-04-15 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_name_vacancies_title_alter_vacancies_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancies',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
