# Generated by Django 6.0.3 on 2026-04-15 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_vacancies_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacancies',
            old_name='known_lnaguages',
            new_name='known_lanaguages',
        ),
    ]
