# Generated by Django 6.0.3 on 2026-04-15 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_known_lnaguages_vacancies_known_lanaguages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacancies',
            old_name='known_lanaguages',
            new_name='known_languages',
        ),
    ]
