# Generated by Django 6.0.3 on 2026-04-16 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_known_lanaguages_vacancies_known_languages'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancies',
            name='location',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
