# Generated by Django 6.0.3 on 2026-04-16 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_vacancies_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancies',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
