# Generated by Django 6.0.3 on 2026-04-16 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_vacancies_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='direction',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
