# Generated by Django 6.0.3 on 2026-04-28 06:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_category_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancies',
            name='company_video',
            field=models.FileField(blank=True, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator('mov, avi')]),
        ),
        migrations.AlterField(
            model_name='vacancies',
            name='salary',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
